name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Selecionar Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Compilar App
        run: |
          xcodebuild \
            -project iOS-SmartWebView.xcodeproj \
            -scheme iOS-SmartWebView \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/NJCI.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

      - name: Gerar IPA
        run: |
          mkdir -p Payload
          cp -R build/NJCI.xcarchive/Products/Applications/*.app Payload/
          mkdir -p build
          zip -r build/NJCI-iOS.ipa Payload

      - name: Enviar IPA
        uses: actions/upload-artifact@v4
        with:
          name: NJCI-iOS
          path: build/NJCI-iOS.ipa
